CREATE SEQUENCE IF NOT EXISTS public.books_id_seq;

CREATE TABLE IF NOT EXISTS public.books
(
    id bigint NOT NULL DEFAULT nextval('books_id_seq'::regclass),
    name character varying(25) COLLATE pg_catalog."default" NOT NULL,
    author character varying(25) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT books_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.books_AUD
(
    id bigint not null,
    REV integer not null,
    REVTYPE smallint,
    name character varying(25) COLLATE pg_catalog."default" NOT NULL,
    primary key (id, REV)
);

CREATE SEQUENCE hibernate_sequence START 1;

create table if not exists REVINFO (
    REV integer generated by default as identity,
    REVTSTMP bigint,
    primary key (REV)
);

alter table books_AUD
    add constraint books_REV
        foreign key (REV)
            references REVINFO;
